//! Shared data models.

use std::path::PathBuf;
use std::time::SystemTime;

/// A filesystem change kind reported by the watcher.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ChangeKind {
    /// A file or directory was created.
    Created,
    /// A file or directory was modified.
    Modified,
    /// A file or directory was deleted.
    Deleted,
    /// A file or directory was renamed.
    Renamed,
}

/// A file change displayed by the TUI and consumed by runtime systems.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FileChange {
    /// Changed filesystem path.
    pub path: PathBuf,
    /// Previous path for rename events.
    pub previous_path: Option<PathBuf>,
    /// Kind of change.
    pub kind: ChangeKind,
    /// Whether the changed path is a directory.
    pub is_directory: bool,
    /// Optional detail lines derived from the changed file type.
    pub detail: Option<ChangeDetail>,
}

/// UI-ready details about a filesystem change.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ChangeDetail {
    /// Text diff preview.
    Text {
        /// Optional line/column summary.
        location: Option<String>,
        /// Diff preview lines.
        preview: Vec<String>,
        /// Whether the preview was truncated.
        truncated: bool,
    },
    /// Media metadata summary.
    Media {
        /// Media family.
        kind: String,
        /// MIME type.
        mime_type: String,
        /// File size in bytes.
        size_bytes: u64,
        /// Additional metadata lines.
        metadata: Vec<String>,
    },
    /// Binary metadata summary.
    Binary {
        /// Previous size in bytes when known.
        previous_size: Option<u64>,
        /// Current size in bytes when known.
        current_size: Option<u64>,
        /// Whether the content hash changed.
        hash_changed: bool,
    },
    /// Deleted file detail.
    Deleted,
}

/// Runtime process state.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProcessState {
    /// The process is being started.
    Starting,
    /// The process is running.
    Running,
    /// The process is being restarted.
    Restarting,
    /// The process is stopped.
    Stopped,
    /// The process failed to start or exited with an error.
    Failed,
}

/// A captured log stream category.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum LogKind {
    /// Standard output from the child process.
    Stdout,
    /// Standard error from the child process.
    Stderr,
    /// Rumon-generated runtime output.
    System,
}

/// A log line captured or generated by Rumon.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LogEntry {
    /// Log category.
    pub kind: LogKind,
    /// Log text.
    pub message: String,
    /// Time when the log was created.
    pub timestamp: SystemTime,
}

impl LogEntry {
    /// Creates a log entry timestamped with the current system time.
    #[must_use]
    pub fn new(kind: LogKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
            timestamp: SystemTime::now(),
        }
    }
}
